version: '3.4'

services:
  oceanica:
    image: ${DOCKER_REGISTRY-}oceanica
    build:
      context: .
      dockerfile: Oceanica/Dockerfile
  
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"
